dist: bionic
language: java
before_install:
- rm ~/.m2/settings.xml
jdk:
- openjdk11
install: mvn -v
script: mvn -B -nsu verify jacoco:report
cache:
  directories:
  - "$HOME/.m2"
branches:
  except:
  - "/^release\\/.*$/"
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
    secure: Ois4xiC43QIzrIIqi0E74E4Y17HQ4f7MV8nH2E1mt1KJ880jtWToaYyTaBRgv/gD4/3FkjEYcczIX2nLxhQYLI6yfFf7RfcBNQ+RTk1p+SWeX0TAbufEQ+r086IrCbPXaMgUB+VfLA2Yi7HEXzYkT97shI93gh5r10G03v1WXNtn4yoggYmBUIrjYuAkQO8+IaebcVmsGu656zTa7EF/wnLvaG2NEGYpKIp7xhkG8zUmF6qger1QSThod0oxAzITPIwymLDBvaRTZwdT5AjU1z4eruTP0QzTok4T3AIeGclABZZoQYCyld+2Z+d2J24jB94BVN5pzu1aewenohpRuBLF9rr4v7xu3iriFfWFbHqdBig8Chf+v8ZqaNWOwT6y7hu+gIiCTQ0623Bp5Cf1x/IAwrud0sZbkAyaceDspz89Em05erLro9ZE3f+1DF47Usn/bxV5CJmIvbBmSldRXiNbNaQbmqzxoeciDgMSsjgtPpE+fNtSK2O0SMzWamHszNc8oAX/LXIMXSEomLTMqhmsrXgXickLCf4uG5bpe/CAsLQ1sW9hLNrU5RZoyqFyRWM6S3VnBK08cQGlGPl/tl7RPr/naFbjdk6xIwC9YnDH2LtvsPE6QPtTpyQDxUYx1YOhJvWG8I5CovWFOIkSc967lG+DJySREaC1BCCjkHs=
